In [67]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()

In [68]:
def weight_variable(shape):
    #initial = tf.truncated_normal(shape, stddev=0)
    initial = tf.constant(1.0, shape=shape)
    
    with tf.Session() as sess:
        print(sess.run(initial))
        
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.0, shape=shape)
    
    with tf.Session() as sess:
        print(sess.run(initial))
        
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='VALID')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2,1], padding='VALID')


In [69]:
w_conv = weight_variable([3,3,1,1])
print(w_conv)

[[[[1.]]

  [[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]

  [[1.]]]]
<tf.Variable 'Variable_19:0' shape=(3, 3, 1, 1) dtype=float32_ref>


In [70]:
b_conv = bias_variable([1])
print(b_conv)

[0.]
<tf.Variable 'Variable_20:0' shape=(1,) dtype=float32_ref>


In [71]:
x = np.array([[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]],'float32')
x_image = tf.reshape(x,[-1,5,5,1])

In [72]:
conv = conv2d(x_image, w_conv) + b_conv
print(conv)

Tensor("add_8:0", shape=(1, 3, 3, 1), dtype=float32)


In [73]:
sess.run(tf.global_variables_initializer())
result = sess.run(conv)
print(result)

[[[[ 54.]
   [ 63.]
   [ 72.]]

  [[ 99.]
   [108.]
   [117.]]

  [[144.]
   [153.]
   [162.]]]]
